---
- name: Test Proxmox API
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Get Proxmox version
      ansible.builtin.uri:
        url: "https://172.16.11.6:8006/api2/json/version"
        method: GET
        validate_certs: false
        headers:
          Authorization: "PVEAPIToken=awx@pve!awx={{ proxmox_token }}"
        return_content: true
      register: proxmox_version

    - name: Show Proxmox version
      ansible.builtin.debug:
        var: proxmox_version.json